version: '3'

services:
  pub-ingestor:
    image: ojjsaw/pub-ingestor
    environment:
    - ZMQ_ADDRESS=tcp://*:3000
    ports:
        - 3000:3000
  sub-worker:
    image: ojjsaw/sub-worker
    environment:
    - ZMQ_ADDRESS=tcp://192.168.131.65:3000
