apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-worker
  labels:
    app: sub-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sub-worker
  template:
    metadata:
      labels:
        app: sub-worker
    spec:
      containers:
      - name: sub-worker
        image: ojjsaw/sub-worker:latest
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always
