apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-worker
  labels:
    app: sub-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sub-worker
  template:
    metadata:
      labels:
        app: sub-worker
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup pub-ingestor; do echo waiting for pub-ingestor; done;']
      containers:
      - name: sub-worker
        image: ojjsaw/sub-worker:latest
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always
